# -------------------------------- #
#                                  #
#                SQL               #
#                                  #
# -------------------------------- #

host: "localhost"
port: "3306"
database: "zoriontp"
username: "root"
password: ""

# Only for experienced users
arguments: "?useSSL=false&allowPublicKeyRetrieval=true"

# -------------------------------- #
#                                  #
#           Permissions            #
#                                  #
# -------------------------------- #

createPermission: "zoriontp.warp.create"
teleportPermission: "zoriontp.warp.tp"
removePermission: "zoriontp.warp.remove"

adminRemovePermission: "zoriontp.admin.remove"

# -------------------------------- #
#                                  #
#             Messages             #
#                                  #
# -------------------------------- #

helpText:
  - "&7/zoriontp&8 -&7 Display the help menu."
  - "&7/zoriontp <warp>&8 -&7 Teleport to a warp."
  - "&7/zoriontp create <warp>&8 -&7 Create a warp."
  - "&7/zoriontp remove <warp>&8 -&7 Remove a warp."

noPermission: "&cYou don't have the permission to execute this command."
missingArgument: "&cIt seems like you forgot to include some useful information."
noOwnership: "&cIt seems like you're not the owner of this playerwarp."

warpCreated: "&7Successfully created playerwarp with name&a {0}."
warpRemoved: "&7Successfully removed playerwarp with name&a {0}."
warpTeleported: "&7Successfully teleported to&a {0}."

warpTaken: "&cA warp with that name already exists or can't be used."
warpUnknown: "&cThis warp doesn't exist."